import random
response = "x"
while response== "x":
    secret=random.randint(1,6)

    if secret ==1:
        print("[---------------]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[       0       ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[---------------]")
    if secret ==2:
        print("[---------------]")
        print("[               ]")
        print("[               ]")
        print("[   0           ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[           0   ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[---------------]")
    if secret ==3:
        print("[---------------]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[    0          ]")
        print("[               ]")
        print("[       0       ]")
        print("[               ]")
        print("[           0   ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[---------------]")
     
    if secret ==4:
        print("[---------------]")
        print("[ 0            0]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[0             0]")
        print("[---------------]")

    if secret ==5:
        print("[---------------]")
        print("[ 0            0]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[       0       ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[0             0]")
        print("[---------------]")

    if secret ==6:
        print("[---------------]")
        print("[0             0]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[0             0]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[               ]")
        print("[0             0]")
        print("[---------------]")

    response = input("Presione aqui para girar el dado una y otra vez y n para salir:")

    print("\n")